scenario:
  environment: scenarios.mumt_aircombat_bvr

agent:
  namespaces: ""
  behavior_tree_xml: "default_bt.xml"

bt_runner:
  bt_tick_rate: 200.0
  bt_visualiser:
    enabled: True
    screen_width: 900
    screen_height: 700
  profiling_mode: False
